apiVersion: build.codearts.crossplane.io/v1alpha1
kind: BuildTask
metadata:
  name: network-crawler-build-task
spec:
  forProvider:
    region: ap-southeast-3
    projectIdRef:
      name: network-simulator-project
    jobName: network-crawler-build
    buildConfigType: ACTION
    sourceCode: codeci
    buildEnvironmentType: docker
    hostType: devcloud
    arch: x86-64
    description: "build task for network-crawler"
    flavor: DEFAULT
    parameters:
      - name: hudson.model.StringParameterDefinition
        params:
          - name: name
            value: IMAGE_TAG
          - name: type
            value: normalparam
          - name: defaultValue
            value: latest
          - name: description
            value: "Docker image tag"
          - name: sensitiveVar
            value: "false"
          - name: staticVar
            value: "false"
          - name: deletion
            value: "false"
          - name: defaults
            value: "false"
    steps:
      - name: Build Image and Push to SWR
        moduleId: devcloud2018.codeci_action_20004.action
        enable: true
        properties:
          registryUrl:
            displayName: SWR
            value: swr.ap-southeast-3.myhuaweicloud.com
          setMetaData: "yes"
          image: docker20.10
          cache: "true"
          imageName: network-crawler
          selectRegion: ap-southeast-3
          contextPath: .
          authUser:
            displayName: Current
            value: current
          dockerFilePath: ./Dockerfile
          organization: fuxi-ci
          tag: ${IMAGE_TAG}
          preCondition: SUCCESS
    scms:
      - repoIdRef:
          name: network-crawler-repo
        branch: master
        scmType: codehub
        buildType: branch
