apiVersion: sample.codearts.crossplane.io/v1alpha1
kind: MyType
metadata:
  name: example-resource
spec:
  forProvider:
    status: "Degraded"
    message: "Manual intervention required: invalid credentials"