apiVersion: apps/v1
kind: Deployment
metadata:
  name: failing-app-1
  labels:
    app: failure-test
spec:
  progressDeadlineSeconds: 1
  replicas: 1
  selector:
    matchLabels:
      app: failure-test
  template:
    metadata:
      labels:
        app: failure-test
    spec:
      containers:
      - name: busybox-script
        image: busybox:latest
        # The 'command' field overrides the ENTRYPOINT
        # The 'args' field provides arguments to that command
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Starting script..."
            sleep 3
            echo "Crashing now with exit code 1"
            exit 1
      
      # Optional: Controls how quickly Kubernetes tries to restart the failing pod
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: failing-app-2
  labels:
    app: failure-test
spec:
  progressDeadlineSeconds: 1
  replicas: 1
  selector:
    matchLabels:
      app: failure-test
  template:
    metadata:
      labels:
        app: failure-test
    spec:
      containers:
      - name: busybox-script
        image: busybox:latest
        # The 'command' field overrides the ENTRYPOINT
        # The 'args' field provides arguments to that command
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Starting script..."
            sleep 3
            echo "Crashing now with exit code 1"
            exit 1
      
      # Optional: Controls how quickly Kubernetes tries to restart the failing pod
      restartPolicy: Always      